name: CI

on: [push, pull_request]

jobs:
  build:
    name: ci
    runs-on: ubuntu-latest
    steps:
    - name: Set repository name to lower case
      run: |
        echo "REPO_NAME_LC=${REPO_NAME,,}" >>${GITHUB_ENV}
      env:
        REPO_NAME: '${{ github.repository }}'

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up docker buildx
      uses: docker/setup-buildx-action@v1

    - name: Setup docker image layer cache
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ env.REPO_NAME_LC }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-${{ env.REPO_NAME_LC }}-
          ${{ runner.os }}-buildx-

    - name: Build docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        tags: ${{ env.REPO_NAME_LC }}:${{ github.sha }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
        outputs: type=docker

    - name: Post build move docker image layer cache
      # temporary fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache

    - name: Run linter >> flake8
      uses: addnab/docker-run-action@v3
      with:
        image: ${{ env.REPO_NAME_LC }}:${{ github.sha }}
        run: flake8
