name: CI

on: [push, pull_request]

jobs:
  build:
    name: build docker image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up docker buildx
      uses: docker/setup-buildx-action@v1

    - name: Setup docker image layer cache
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.repository }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-${{ github.repository }}-
          ${{ runner.os }}-buildx-

    - name: Build docker image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: ${{ github.repository }}:${{ github.sha }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
        outputs: type=docker,dest=/tmp/image.tar

    - name: Post build move docker image layer cache
      # temporary fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: image
        path: /tmp/image.tar

  tests:
    name: test
    needs: build
    steps:
      - uses: docker/setup-buildx-action@v1
      - uses: actions/download-artifact@v2
        with:
          name: image
          path: /tmp
      - run: docker load --input /tmp/image.tar
      - uses: ./.github/workflows/run-tests.yml
        with:
          docker-image-tag: ${{ github.repository }}:${{ github.sha }}
