name: CI tests

on:
  workflow_call:
    inputs:
      docker-image-tag:
        required: true
        type: string

jobs:
  lint-flake8:
    name: lint / flake8
    runs-on: ubuntu-latest
    steps:
    - uses: docker://${{ inputs.docker-image-tag }}

#  type-check-mypy:
#    name: type check / mypy
#    runs-on: ubuntu-latest
#    steps:
#    - run: docker run ${{ inputs.docker_image_tag }} mypy
#
#  unit-test-pytest:
#    name: unit test / pytest
#    runs-on: ubuntu-latest
#    steps:
#    - run: |
#        docker run ${{ inputs.docker_image_tag }} pytest
