name: CI tests

on:
  workflow_run:
    workflows: [CI build]
    types: [completed]

jobs:
  lint-flake8:
    runs-on: ubuntu-latest
    steps:
    - name: Run code linter - flake8
      env:
        $DOCKER_IMAGE_TAG: ${{ github.repository }}:${{ github.sha }}
      run: |
        docker run $DOCKER_IMAGE_TAG flake8

#  type-check-mypy:
#    runs-on: ubuntu-latest
#    steps:
#    - name: Run static type checker - mypy
#      env:
#        $DOCKER_IMAGE_TAG: ${{ github.repository }}:${{ github.sha }}
#      run: |
#        docker run $DOCKER_IMAGE_TAG mypy
#
#  unit-test-pytest:
#    runs-on: ubuntu-latest
#    steps:
#    - name: Run unit tests - pytest
#      env:
#        $DOCKER_IMAGE_TAG: ${{ github.repository }}:${{ github.sha }}
#      run: |
#        docker run $DOCKER_IMAGE_TAG pytest
