name: CI tests

on:
  workflow_run:
    workflows: [CI build]
    types: [completed]

jobs:
  lint-flake8:
    name: Run code linter - flake8
    runs-on: ubuntu-latest
    steps:
    - env:
        $DOCKER_IMAGE_TAG: ${{ github.event.repository }}:${{ github.event.sha }}
      run: |
        docker run $DOCKER_IMAGE_TAG flake8

#  type-check-mypy:
#    name: Run static type checker - mypy
#    runs-on: ubuntu-latest
#    steps:
#    - env:
#        $DOCKER_IMAGE_TAG: ${{ github.repository }}:${{ github.sha }}
#      run: |
#        docker run $DOCKER_IMAGE_TAG mypy
#
#  unit-test-pytest:
#    name: Run unit tests - pytest
#    runs-on: ubuntu-latest
#    steps:
#    - env:
#        $DOCKER_IMAGE_TAG: ${{ github.repository }}:${{ github.sha }}
#      run: |
#        docker run $DOCKER_IMAGE_TAG pytest
